# Generated by Django 3.2.17 on 2023-06-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredlyCourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(default='', max_length=100)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credly_course_data', to='course_overviews.courseoverview')),
            ],
        ),
    ]
