# Generated by Django 3.2.19 on 2023-07-08 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduserprofile',
            name='career_stage',
            field=models.CharField(choices=[('college_student', 'College student'), ('graduate_student', 'Graduate student'), ('less_than_5_years', '<5 years highest degree'), ('5_to_10_years', '5-10 years highest degree'), ('more_than_10_years', '10+ years highest degree')], default='college_student', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extendeduserprofile',
            name='extended_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer not to say / My option is not listed')], default='prefer_not_to_say', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extendeduserprofile',
            name='orcid_id',
            field=models.CharField(default='none', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}-\\d{4}-\\d{4}$|^none$', message="ORCID ID must be in the format: '0000-0000-0000-0000' or 'none'")]),
        ),
        migrations.AddField(
            model_name='extendeduserprofile',
            name='race_ethnicity',
            field=models.CharField(choices=[('american_indian', 'American Indian or Alaskan Native'), ('asian', 'Asian'), ('black', 'Black or African American'), ('hispanic_latino', 'Hispanic or Latino'), ('white', 'White'), ('prefer_not_to_say', 'Prefer not to say / My option is not listed')], default='prefer_not_to_say', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extendeduserprofile',
            name='science_community',
            field=models.CharField(choices=[('astrophysics', 'Astrophysics'), ('bio_physical_sciences', 'Biological and Physical Sciences'), ('earth_science', 'Earth Science'), ('heliophysics', 'Heliophysics'), ('planetary_science', 'Planetary Science'), ('other', 'Other')], default='other', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extendeduserprofile',
            name='subscribe_to_emails',
            field=models.BooleanField(default=False),
        ),
    ]
